---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bisadtra/public_html/
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R rs-plugin $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp gallery.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
